# Configuration for support-requests - https://github.com/dessant/support-requests

# Label used to mark issues as support requests
supportLabel: support

# Comment to post on issues marked as support requests. Add a link
# to a support page, or set to `false` to disable
supportComment: >
  We use GitHub exclusively for bug reports and feature requests.
  However, this issue appears to be a support request. Please use our
  [community forum](http://discourse.pressbooks.org) to get help with Pressbooks.

# Close issues marked as support requests
close: true

# Lock issues marked as support requests
lock: true
