codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: yes
    patch: yes
    changes: no

  notify:
    slack:
      default:
        url: "secret:/oj/A552M7JoclWHak5KXY5DO66SFEZlJcFZLuoPRqiOZK4mHKAGHa4hiSjgWwXTIVzWP2ACNNZnbX5q/QPPUdjWkwk1LpavnvmA9EsmRZBgjWaPJgcXmNSDg2UHM74kT4Nl17TX8RAJ0c2aABuPycxPuz43y2lw+f3CfTv/rLs="
        threshold: 1%
parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no
