# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pressbooks Documentation
email: code@pressbooks.com
description: > # this means to ignore newlines until "baseurl:"
  Documentation for the Pressbooks Open Source project.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://docs.pressbooks.org/" # the base hostname & protocol for your site
twitter_username: pressbooks
github_username:  pressbooks

# Build settings
markdown: kramdown
