name: Run Standards

on:
  push:
    branches: [dev, production]
  pull_request:
    branches: [dev]

jobs:
  standards:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [8.1]

    name: Standards - PHP ${{ matrix.php }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache Composer packages
      uses: actions/cache@v4
      with:
        path: vendor
        key: ${{ matrix.php }}-php-${{ hashFiles('**/composer.lock') }}

    - name: Setup PHP with Composer 2
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        tools: composer
        coverage: none

    - name: Install PHP dependencies
      run: |
        export PATH="$HOME/.composer/vendor/bin:$PATH"
        composer install --no-interaction
        ulimit -n 4096

    - name: Run PHP CodeSniffer
      run: composer standards
